import "colors";
import { RootAppPath, ReadGpxFile, GetStringBetweenIncludedPatterns, MergeStagesTrack, GetString, GetLinkTrk, GetExtensions, GetTracks, GetRoutes, GetWayPoints, DataExtraction, SplitString, GetCumulativeElevations, ConvertPositionsToArr, GetPositionsArr, GetElevationArr, GetTagsValueArr, GetBounds, GetLink, GetMetaData, CalculateDistanceBetweenPositions, TrackDistanceCalculation } from '../types/gpsLibType';
declare const rootAppPath: RootAppPath;
declare const readGpxFile: ReadGpxFile;
declare const getStringBetweenIncludedPatterns: GetStringBetweenIncludedPatterns;
declare const mergeStagesTrackData: MergeStagesTrack;
declare const getString: GetString;
declare const getLinkTrk: GetLinkTrk;
declare const getExtensions: GetExtensions;
declare const getTracks: GetTracks;
declare const getRoutes: GetRoutes;
declare const getWayPoints: GetWayPoints;
declare const dataExtraction: DataExtraction;
declare const splitString: SplitString;
declare const getCumulativeElevations: GetCumulativeElevations;
declare const convertPositionsToArr: ConvertPositionsToArr;
declare const getPositionsArr: GetPositionsArr;
declare const getElevationsArr: GetElevationArr;
declare const getTagsValueArr: GetTagsValueArr;
declare const getBounds: GetBounds;
declare const getLink: GetLink;
declare const getMetaData: GetMetaData;
declare const calculateDistanceBetweenPositions: CalculateDistanceBetweenPositions;
declare const trackDistanceCalculation: TrackDistanceCalculation;
export { rootAppPath, readGpxFile, getStringBetweenIncludedPatterns, mergeStagesTrackData, getString, getLinkTrk, getExtensions, getTracks, getRoutes, getWayPoints, dataExtraction, splitString, getCumulativeElevations, convertPositionsToArr, getPositionsArr, getElevationsArr, getTagsValueArr, getBounds, getLink, getMetaData, calculateDistanceBetweenPositions, trackDistanceCalculation };
